# Generated by Django 3.1.14 on 2022-05-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_pokemon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lattitude', models.FloatField(verbose_name='Lat.')),
                ('longitude', models.FloatField(verbose_name='Lon.')),
            ],
        ),
    ]
