# Generated by Django 3.1.14 on 2022-05-06 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20220506_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя англ.'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_jap',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя яп.'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 11, 12, 9, 731766, tzinfo=utc)),
        ),
    ]
